version: '3.8'

services:
  php:
    build: .
    container_name: hotel-ikin-php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/logs:/var/log/apache2
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: hotel-ikin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_ikin
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hotel-ikin-pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: